import os
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT_DIR / "data"

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
VECTOR_DIM = int(os.getenv("VECTOR_DIM", "768"))
PGVECTOR_PROBES = int(os.getenv("PGVECTOR_PROBES", "10"))
TEMP_LIVE_DIR = str(DATA_DIR / "temp_live_chunks")
TEMP_SEARCH_UPLOAD_DIR = str(DATA_DIR / "temp_search_uploads")
TEMP_SEARCH_DOWNLOAD_DIR = str(DATA_DIR / "temp_search_downloads")
TEMP_SEARCH_PREPROCESS_DIR = str(DATA_DIR / "temp_search")
TIKTOK_DOWNLOAD_TIMEOUT_SECONDS = 90
TIKTOK_MAX_FILE_MB = 200
SEARCH_MAX_DURATION_SECONDS_PUBLIC = 180
SEARCH_MAX_DURATION_SECONDS_ADMIN: int | None = None

INGEST_CHUNK_SECONDS = 60
MONITOR_POLL_SECONDS = 30.0
SESSION_POLL_INTERVAL = 0.5
MONITOR_RETRY_SECONDS = 5.0

LIVE_ARCHIVE_LAG_SECONDS = 120
LIVE_ARCHIVE_POLL_SECONDS = 15.0
LIVE_ARCHIVE_FINALIZE_CHECKS = 3

LIVE_SESSIONS_DEFAULT_LIMIT = 50
LIVE_SESSIONS_MAX_LIMIT = 200

TWITCH_EVENTSUB_SECRET = os.getenv("TWITCH_EVENTSUB_SECRET", "").strip()
TWITCH_EVENTSUB_CALLBACK_URL = os.getenv("TWITCH_EVENTSUB_CALLBACK_URL", "").strip()
EVENTSUB_RECONCILE_SECONDS = float(os.getenv("EVENTSUB_RECONCILE_SECONDS", "300"))
EVENTSUB_FALLBACK_POLL_SECONDS = float(os.getenv("EVENTSUB_FALLBACK_POLL_SECONDS", "120"))
EVENTSUB_MESSAGE_TTL_SECONDS = int(os.getenv("EVENTSUB_MESSAGE_TTL_SECONDS", "600"))
EVENTSUB_MAX_CLOCK_SKEW_SECONDS = int(os.getenv("EVENTSUB_MAX_CLOCK_SKEW_SECONDS", "600"))
PUBLIC_API_ORIGIN = os.getenv("PUBLIC_API_ORIGIN", "").strip()
ADMIN_API_ORIGIN = os.getenv("ADMIN_API_ORIGIN", "").strip()


def validate_storage_config() -> None:
    if not DATABASE_URL:
        raise ValueError("DATABASE_URL is required")
